name: Update SJP Data

on:
  schedule:
    - cron: '30 21 * * *'      # 21:30 UTC daily  (= 22:30 BST)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # allow push via GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker
        run: python sjp_flow_tracker.py

      - name: Commit & push CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          if git diff --cached --quiet; then
            echo "No changes – skipping commit."
          else
            git commit -m "auto: update data $(date -u +'%Y-%m-%d')"
            git push
          fi
